---
title: "Data Visualization"
output: html_document
---

```{r}
# Import libraries
library(tidyverse)
install.packages("gghighlight")
library(gghighlight)

```

```{r}
# Import data
lfp <- read.csv("lfs.csv", sep = ";", dec = ",") %>% select(Country, Sex, Time, Value)

lfp_orig <- lfp

wlfp <- lfp %>% 
  filter(Sex == "Women") %>% 
  mutate(Time = factor(Time, levels = c(1980, 2017))) %>% 
  ggplot(aes(x=Country, y=Value, fill = Time)) +
  geom_col(position = "dodge") +
  labs(x = NULL,
       y = "Percent") +
  scale_fill_manual(values = c("turquoise3", "turquoise4")) +
  theme_minimal() +
  theme(legend.title = element_blank(),
        panel.background = element_rect(fill = "white", colour = "grey50"),
        panel.spacing = unit(1, "lines"),
        panel.grid.major.x = element_blank(),
        axis.text.y = element_text(size = 13),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        strip.text = element_text(size = 13),
        legend.background = element_rect(color = "grey")) 

print(wlfp)

ggsave("wlfp.png", height = 8, width = 12)


theme_flip <- theme(panel.background = element_rect(fill = "white"),
        axis.text = element_text(size = 25, face = "bold"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = rel(1)),
        axis.ticks = element_blank(),
        axis.line.y = element_line(colour = "grey"),
        #plot.title = element_text(size=15, hjust = 0, vjust=2.12),
        legend.position = "bottom",
        legend.title = element_blank(),
        legend.text = element_text(size = 22),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(hjust = 0),
        plot.background = element_rect(fill = "white"),
        plot.caption = element_text(size = 14, face = "italic"),
        strip.text.x = element_text(size = 11, face = "bold"))
```

